#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
#set -o xtrace

DIR=~/.config
LINKME="
Xresources
bash_profile
bashrc
compton.conf
gitconfig
gitignore
gtkrc-2.0
i3
i3status.conf
pythonrc
tmux
tmux.conf
vim
vimrc
xonshrc
"

git-create-update() {
	curl https://raw.githubusercontent.com/dryvenn/scripts/master/git-create-update | bash -s $@
}

git-create-update $DIR https://github.com/dryvenn/config

for l in $LINKME
do
	ln -svnf $DIR/$l ~/.$l
done

echo "Installing vim plugins..."
vim +PlugInstall +qall &> /dev/null

echo "Done."
