#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
#set -o xtrace

cd $(dirname $0)

# Get latest changes from Git
stash=$(git stash create -kua)
git reset --hard
git pull --rebase origin master
git submodule update --init
if [ -n "$stash" ]
then
	git stash apply $stash
fi

# Link dotfiles
for l in $(find $PWD/.homepoline -mindepth 1)
do
	ln -svnf $l ~/.$(basename $l)
done

echo "Installing vim plugins..."
vim +PlugInstall +PlugUgrade +PlugUpdate +qall &> /dev/null

echo "Installing tmux plugins..."
~/.tmux/plugins/tpm/bin/install_plugins &> /dev/null
~/.tmux/plugins/tpm/bin/update_plugins all &> /dev/null

echo "Installing fzf..."
~/.config/fzf/install --all &> /dev/null

echo "Compiling kakoune..."
make -j $(nproc) -C kak/kakoune/src &> /dev/null
mkdir -p ~/.local/bin
ln -snf $PWD/kak/kakoune/src/kak ~/.local/bin/kak

echo "Done."
