#!/usr/bin/env bash

DIR=$(dirname $(readlink -f $0))

targets="
tmux.conf
tmux
gitconfig
gitconfig_local
pythonrc
"

cd ~
for target in $targets
do
    ln -s -v $DIR/$target .$target
done

ln -s -v $(dirname $(dirname $(readlink -f $(which kak))))/share/kak/rc ~/.config/kak/autoload/
