# Theme
colorscheme zenburn
addhl global/ number_lines
addhl global/ show_matching
addhl global/ show_whitespaces -tab "»" -tabpad " " -lf " " -spc " " -nbsp "·"

# UI
set-option -add global ui_options "ncurses_assistant=off"
set-option -add global ui_options "ncurses_set_title=true"
set-option -add global ui_options "ncurses_enable_mouse=false"

# Search highlighting
set global incsearch true

# Case-insensitive search
map -docstring 'Case-insensitive search' global user '/' /(?i)
map -docstring 'Case-insensitive reverse search' global user '<a-/>' <a-/>(?i)
map -docstring 'Case-insensitive search (extend)' global user '?' ?(?i)
map -docstring 'Case-insensitive reverse search (extend)' global user '<a-?>' <a-?>(?i)

# Simple file finder
define-command -docstring 'find <file>: find a file' \
    -params 1 \
    -shell-candidates %{ find . -type f } \
    find %{
        edit %arg{1}
    }

# Git file finder
define-command -docstring 'gitf <pattern>: git file finder' \
    -params 1 \
    -shell-candidates %{ git ls-files } \
    gitf %{
        edit %arg{1}
    }

# FZF file finder
define-command -docstring 'fzf: FZF file invocation' \
    -params 0 \
    fzf-file %{ evaluate-commands %sh{
        if [ -z "$TMUX" ]; then
            echo "echo -markup \"{Error}Only works inside tmux\""
            exit
        fi
        f=$(find * -type f | fzf-tmux -d 20%)
        if [ -n "$f" ]
        then
            printf 'edit! %%{%s}\n' $f
        fi
    }}
map global normal <c-f> ':fzf-file<ret>'

# FZF buffer finder
define-command -docstring 'fzf: FZF buffer invocation' \
    -params 0 \
    fzf-buffer %{ evaluate-commands %sh{
        if [ -z "$TMUX" ]; then
            echo "echo -markup \"{Error}Only works inside tmux\""
            exit
        fi
        b=$(echo "$kak_buflist" | tr ' ' '\n' | tr -d "'" | fzf-tmux -d 20%)
        if [ -n "$b" ]
        then
            printf 'buffer %s\n' $b
        fi
    }}
map global normal <c-b> ':fzf-buffer<ret>'

# Show trailing whitespaces
addhl global/ dynregex "[^\S\n]+$" 0:black,red

# Strip trailing whitespaces
define-command -docstring 'strip-tws: strip trailing whitespaces' \
    -params 0 \
    strip-tws %{
        exec -draft %{ %s[^\S\n]+$<ret>d }
    }

# Wrap at 80
hook global WinCreate .* %{ autowrap-enable }

# kakoune-cscope mappings
map -docstring 'Find this C symbol'                     global user 's' '<a-i>w:cscope 0 <c-r>.<ret>'
map -docstring 'Find this function definition'          global user 'g' '<a-i>w:cscope 1 <c-r>.<ret>'
map -docstring 'Find functions called by this function' global user 'd' '<a-i>w:cscope 2 <c-r>.<ret>'
map -docstring 'Find functions calling this function'   global user 'c' '<a-i>w:cscope 3 <c-r>.<ret>'
map -docstring 'Find this text string'                  global user 't' '<a-i>w:cscope 4 <c-r>.<ret>'
map -docstring 'Find this egrep pattern'                global user 'e' '<a-i>w:cscope 6 <c-r>.<ret>'
map -docstring 'Find this file'                         global user 'f' '<a-i>w:cscope 7 <c-r>.<ret>'
map -docstring 'Find files #including this file'        global user 'i' '<a-i>w:cscope 8 <c-r>.<ret>'
map -docstring 'Find assignments to this symbol'        global user 'a' '<a-i>w:cscope 9 <c-r>.<ret>'

# Search with Ag
set-option global grepcmd 'ag --vimgrep'
map global normal <c-k> '<a-i>w:grep <c-r>.<ret>'
